name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby:
        - 3.0
        - 2.7
        - 2.6
        - debug
        include:
        - { os: windows-latest , ruby: mingw }
        - { os: windows-latest , ruby: mswin }
        exclude:
        - { os: windows-latest , ruby: 3.0 }
        - { os: windows-latest , ruby: debug }

    steps:
    - uses: actions/checkout@v1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: bundle install --jobs 4 --retry 3

    - run: rake test

    - run: rake build

    - run: gem install pkg/*.gem
